### ISSUE TITLE
Missing serve-static dependency

### ISSUE THREAD

**Issue by lubo** [ritiek/play-on-kodi#2]
Hello, I get this error when trying to run `$ playonkodi`:

```
module.js:491
    throw err;
    ^

Error: Cannot find module 'serve-static'
    at Function.Module._resolveFilename (module.js:489:15)
    at Function.Module._load (module.js:439:25)
    at Module.require (module.js:517:17)
    at require (internal/module.js:11:18)
    at Object.<anonymous> (/home/lubo/.npm-packages/lib/node_modules/playonkodi/bin/playonkodi.js:8:19)
    at Module._compile (module.js:573:30)
    at Object.Module._extensions..js (module.js:584:10)
    at Module.load (module.js:507:32)
    at tryModuleLoad (module.js:470:12)
    at Function.Module._load (module.js:462:3)
```

I'm on Arch Linux, Node.js 8.4.0. Installed using `$ npm install -g playonkodi`.

**Comment by ritiek** [comment]
I thought it was already included with vanilla node. Anyway, this should be fixed now. Try running `npm install -g playonkodi` again.

**Comment by lubo** [comment]
Seems to be fixed.
